FROM ubuntu:18.04

# CMD ["sleep", "5", "", "", ""]
# first argument have to be executable

# CMD sleep 4 
# shell format

# CMD ["sleep", "4"]
# CMD can recieve override commands like "sleep 1"

ENTRYPOINT ["sleep"]
# acts at bash command writing sleep and waiting for the length 
# if there is no value added then the bash command sends missing operand message 

CMD ["2"]
# sets value 2 as default if there s no value entered it s taken as operand
 