FROM node:14.15-slim

WORKDIR /opt/twitter-clone
COPY . /opt/twitter-clone

ENV ACCESS_TOKEN_SECRET=32083HDWENCSDCJSDNCS
ENV REFRESH_TOKEN_SECRET= huwef9028fwpefne02heınc20
ENV AWS_ID=ASDJISOİFJDİSJFA
ENV AWS_SECRET=ifcıoirhevi0r9er9034ufcnıo3f
ENV AWS_BUCKET_NAME=twitter-cloene-images-2
ENV PASSWORD_HASH=ffewıorf0923f0ıfno2f302f02hf
ENV PORT 3000

RUN npm install
CMD ["npm", "start"]